title: Sehba's Portfolio
url: "https://sehbaw.github.io"
baseurl: "/swani"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "about.html"
 - name: "Portfolio"
 - name: "Contact"
   link: "contact"
